language: node_js
node_js:
  - 0.10
install:
  - sudo -H $(which npm) install -g mocha bower karma-cli gulp
  - bower install
  - npm install
after_success:
  - mkdir /home/travis/tmp
  - gulp build
  - sudo $(which npm) install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy; fi
